version: '3.8'

services:
  db:
    image: postgres:12.2-alpine
    container_name: "myBank"
    ports:
      -"5432:5432"
    environment:
      -POSTGRES_DB=myBank
      -POSTGRES_USER=postgres
      -POSTGRES_PASSWORD=admin

  app:
    build: .
    container_name: "sanberhub-test"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "admin"
      DB_DB: "myBank"
      DB_HOST: "localhost"
      DB_PORT: "5432"
    ports:
      -"5000:5000"
    depends_on:
      - localhost
    